name: Test
on:
  push:
    branches:
      - main
  pull_request:
env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: |
            7.x
            8.x
            9.x
      - run: dotnet format --verify-no-changes
      - run: dotnet format --verify-no-changes
        working-directory: snapshots/input/syntax
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: |
            6.x
            7.x
            8.x
            9.x
      - run: dotnet test -p:TargetFrameworks=net9.0
      - run: dotnet test -p:TargetFrameworks=net8.0
      - run: dotnet test -p:TargetFrameworks=net7.0
      - run: dotnet test -p:TargetFrameworks=net6.0
